/**
 * @license
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function () {
  'use strict';

  /**
   * Class constructor for Ripple MDL component.
   * Implements MDL component design pattern defined at:
   * https://github.com/jasonmayes/mdl-component-design-pattern
   *
   * @constructor
   * @param {HTMLElement} element The element that will be upgraded.
   */

  var MaterialRipple = function MaterialRipple(element) {
    this.element_ = element;

    // Initialize instance.
    this.init();
  };
  window['MaterialRipple'] = MaterialRipple;

  /**
   * Store constants in one place so they can be updated easily.
   *
   * @enum {string | number}
   * @private
   */
  MaterialRipple.prototype.Constant_ = {
    INITIAL_SCALE: 'scale(0.0001, 0.0001)',
    INITIAL_SIZE: '1px',
    INITIAL_OPACITY: '0.4',
    FINAL_OPACITY: '0',
    FINAL_SCALE: ''
  };

  /**
   * Store strings for class names defined by this component that are used in
   * JavaScript. This allows us to simply change it in one place should we
   * decide to modify at a later date.
   *
   * @enum {string}
   * @private
   */
  MaterialRipple.prototype.CssClasses_ = {
    RIPPLE_CENTER: 'mdl-ripple--center',
    RIPPLE_EFFECT_IGNORE_EVENTS: 'mdl-js-ripple-effect--ignore-events',
    RIPPLE: 'mdl-ripple',
    IS_ANIMATING: 'is-animating',
    IS_VISIBLE: 'is-visible'
  };

  /**
   * Handle mouse / finger down on element.
   *
   * @param {Event} event The event that fired.
   * @private
   */
  MaterialRipple.prototype.downHandler_ = function (event) {
    if (!this.rippleElement_.style.width && !this.rippleElement_.style.height) {
      var rect = this.element_.getBoundingClientRect();
      this.boundHeight = rect.height;
      this.boundWidth = rect.width;
      this.rippleSize_ = Math.sqrt(rect.width * rect.width + rect.height * rect.height) * 2 + 2;
      this.rippleElement_.style.width = this.rippleSize_ + 'px';
      this.rippleElement_.style.height = this.rippleSize_ + 'px';
    }

    this.rippleElement_.classList.add(this.CssClasses_.IS_VISIBLE);

    if (event.type === 'mousedown' && this.ignoringMouseDown_) {
      this.ignoringMouseDown_ = false;
    } else {
      if (event.type === 'touchstart') {
        this.ignoringMouseDown_ = true;
      }
      var frameCount = this.getFrameCount();
      if (frameCount > 0) {
        return;
      }
      this.setFrameCount(1);
      var bound = event.currentTarget.getBoundingClientRect();
      var x;
      var y;
      // Check if we are handling a keyboard click.
      if (event.clientX === 0 && event.clientY === 0) {
        x = Math.round(bound.width / 2);
        y = Math.round(bound.height / 2);
      } else {
        var clientX = event.clientX !== undefined ? event.clientX : event.touches[0].clientX;
        var clientY = event.clientY !== undefined ? event.clientY : event.touches[0].clientY;
        x = Math.round(clientX - bound.left);
        y = Math.round(clientY - bound.top);
      }
      this.setRippleXY(x, y);
      this.setRippleStyles(true);
      window.requestAnimationFrame(this.animFrameHandler.bind(this));
    }
  };

  /**
   * Handle mouse / finger up on element.
   *
   * @param {Event} event The event that fired.
   * @private
   */
  MaterialRipple.prototype.upHandler_ = function (event) {
    // Don't fire for the artificial "mouseup" generated by a double-click.
    if (event && event.detail !== 2) {
      // Allow a repaint to occur before removing this class, so the animation
      // shows for tap events, which seem to trigger a mouseup too soon after
      // mousedown.
      window.setTimeout(function () {
        this.rippleElement_.classList.remove(this.CssClasses_.IS_VISIBLE);
      }.bind(this), 0);
    }
  };

  /**
   * Initialize element.
   */
  MaterialRipple.prototype.init = function () {
    if (this.element_) {
      var recentering = this.element_.classList.contains(this.CssClasses_.RIPPLE_CENTER);
      if (!this.element_.classList.contains(this.CssClasses_.RIPPLE_EFFECT_IGNORE_EVENTS)) {
        this.rippleElement_ = this.element_.querySelector('.' + this.CssClasses_.RIPPLE);
        this.frameCount_ = 0;
        this.rippleSize_ = 0;
        this.x_ = 0;
        this.y_ = 0;

        // Touch start produces a compat mouse down event, which would cause a
        // second ripples. To avoid that, we use this property to ignore the first
        // mouse down after a touch start.
        this.ignoringMouseDown_ = false;

        this.boundDownHandler = this.downHandler_.bind(this);
        this.element_.addEventListener('mousedown', this.boundDownHandler);
        this.element_.addEventListener('touchstart', this.boundDownHandler);

        this.boundUpHandler = this.upHandler_.bind(this);
        this.element_.addEventListener('mouseup', this.boundUpHandler);
        this.element_.addEventListener('mouseleave', this.boundUpHandler);
        this.element_.addEventListener('touchend', this.boundUpHandler);
        this.element_.addEventListener('blur', this.boundUpHandler);

        /**
         * Getter for frameCount_.
         * @return {number} the frame count.
         */
        this.getFrameCount = function () {
          return this.frameCount_;
        };

        /**
         * Setter for frameCount_.
         * @param {number} fC the frame count.
         */
        this.setFrameCount = function (fC) {
          this.frameCount_ = fC;
        };

        /**
         * Getter for rippleElement_.
         * @return {Element} the ripple element.
         */
        this.getRippleElement = function () {
          return this.rippleElement_;
        };

        /**
         * Sets the ripple X and Y coordinates.
         * @param  {number} newX the new X coordinate
         * @param  {number} newY the new Y coordinate
         */
        this.setRippleXY = function (newX, newY) {
          this.x_ = newX;
          this.y_ = newY;
        };

        /**
         * Sets the ripple styles.
         * @param  {boolean} start whether or not this is the start frame.
         */
        this.setRippleStyles = function (start) {
          if (this.rippleElement_ !== null) {
            var transformString;
            var scale;
            var size;
            var offset = 'translate(' + this.x_ + 'px, ' + this.y_ + 'px)';

            if (start) {
              scale = this.Constant_.INITIAL_SCALE;
              size = this.Constant_.INITIAL_SIZE;
            } else {
              scale = this.Constant_.FINAL_SCALE;
              size = this.rippleSize_ + 'px';
              if (recentering) {
                offset = 'translate(' + this.boundWidth / 2 + 'px, ' + this.boundHeight / 2 + 'px)';
              }
            }

            transformString = 'translate(-50%, -50%) ' + offset + scale;

            this.rippleElement_.style.webkitTransform = transformString;
            this.rippleElement_.style.msTransform = transformString;
            this.rippleElement_.style.transform = transformString;

            if (start) {
              this.rippleElement_.classList.remove(this.CssClasses_.IS_ANIMATING);
            } else {
              this.rippleElement_.classList.add(this.CssClasses_.IS_ANIMATING);
            }
          }
        };

        /**
         * Handles an animation frame.
         */
        this.animFrameHandler = function () {
          if (this.frameCount_-- > 0) {
            window.requestAnimationFrame(this.animFrameHandler.bind(this));
          } else {
            this.setRippleStyles(false);
          }
        };
      }
    }
  };

  // The component registers itself. It can assume componentHandler is available
  // in the global scope.
  componentHandler.register({
    constructor: MaterialRipple,
    classAsString: 'MaterialRipple',
    cssClass: 'mdl-js-ripple-effect',
    widget: false
  });
})();
//# sourceMappingURL=data:application/json;charset=utf8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInJpcHBsZS5qcyJdLCJuYW1lcyI6WyJNYXRlcmlhbFJpcHBsZSIsImVsZW1lbnQiLCJlbGVtZW50XyIsImluaXQiLCJ3aW5kb3ciLCJwcm90b3R5cGUiLCJDb25zdGFudF8iLCJJTklUSUFMX1NDQUxFIiwiSU5JVElBTF9TSVpFIiwiSU5JVElBTF9PUEFDSVRZIiwiRklOQUxfT1BBQ0lUWSIsIkZJTkFMX1NDQUxFIiwiQ3NzQ2xhc3Nlc18iLCJSSVBQTEVfQ0VOVEVSIiwiUklQUExFX0VGRkVDVF9JR05PUkVfRVZFTlRTIiwiUklQUExFIiwiSVNfQU5JTUFUSU5HIiwiSVNfVklTSUJMRSIsImRvd25IYW5kbGVyXyIsImV2ZW50IiwicmlwcGxlRWxlbWVudF8iLCJzdHlsZSIsIndpZHRoIiwiaGVpZ2h0IiwicmVjdCIsImdldEJvdW5kaW5nQ2xpZW50UmVjdCIsImJvdW5kSGVpZ2h0IiwiYm91bmRXaWR0aCIsInJpcHBsZVNpemVfIiwiTWF0aCIsInNxcnQiLCJjbGFzc0xpc3QiLCJhZGQiLCJ0eXBlIiwiaWdub3JpbmdNb3VzZURvd25fIiwiZnJhbWVDb3VudCIsImdldEZyYW1lQ291bnQiLCJzZXRGcmFtZUNvdW50IiwiYm91bmQiLCJjdXJyZW50VGFyZ2V0IiwieCIsInkiLCJjbGllbnRYIiwiY2xpZW50WSIsInJvdW5kIiwidW5kZWZpbmVkIiwidG91Y2hlcyIsImxlZnQiLCJ0b3AiLCJzZXRSaXBwbGVYWSIsInNldFJpcHBsZVN0eWxlcyIsInJlcXVlc3RBbmltYXRpb25GcmFtZSIsImFuaW1GcmFtZUhhbmRsZXIiLCJiaW5kIiwidXBIYW5kbGVyXyIsImRldGFpbCIsInNldFRpbWVvdXQiLCJyZW1vdmUiLCJyZWNlbnRlcmluZyIsImNvbnRhaW5zIiwicXVlcnlTZWxlY3RvciIsImZyYW1lQ291bnRfIiwieF8iLCJ5XyIsImJvdW5kRG93bkhhbmRsZXIiLCJhZGRFdmVudExpc3RlbmVyIiwiYm91bmRVcEhhbmRsZXIiLCJmQyIsImdldFJpcHBsZUVsZW1lbnQiLCJuZXdYIiwibmV3WSIsInN0YXJ0IiwidHJhbnNmb3JtU3RyaW5nIiwic2NhbGUiLCJzaXplIiwib2Zmc2V0Iiwid2Via2l0VHJhbnNmb3JtIiwibXNUcmFuc2Zvcm0iLCJ0cmFuc2Zvcm0iLCJjb21wb25lbnRIYW5kbGVyIiwicmVnaXN0ZXIiLCJjb25zdHJ1Y3RvciIsImNsYXNzQXNTdHJpbmciLCJjc3NDbGFzcyIsIndpZGdldCJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBaUJBLENBQUMsWUFBVztBQUNWOztBQUVBOzs7Ozs7Ozs7QUFRQSxNQUFJQSxpQkFBaUIsU0FBU0EsY0FBVCxDQUF3QkMsT0FBeEIsRUFBaUM7QUFDcEQsU0FBS0MsUUFBTCxHQUFnQkQsT0FBaEI7O0FBRUE7QUFDQSxTQUFLRSxJQUFMO0FBQ0QsR0FMRDtBQU1BQyxTQUFPLGdCQUFQLElBQTJCSixjQUEzQjs7QUFFQTs7Ozs7O0FBTUFBLGlCQUFlSyxTQUFmLENBQXlCQyxTQUF6QixHQUFxQztBQUNuQ0MsbUJBQWUsdUJBRG9CO0FBRW5DQyxrQkFBYyxLQUZxQjtBQUduQ0MscUJBQWlCLEtBSGtCO0FBSW5DQyxtQkFBZSxHQUpvQjtBQUtuQ0MsaUJBQWE7QUFMc0IsR0FBckM7O0FBUUE7Ozs7Ozs7O0FBUUFYLGlCQUFlSyxTQUFmLENBQXlCTyxXQUF6QixHQUF1QztBQUNyQ0MsbUJBQWUsb0JBRHNCO0FBRXJDQyxpQ0FBNkIscUNBRlE7QUFHckNDLFlBQVEsWUFINkI7QUFJckNDLGtCQUFjLGNBSnVCO0FBS3JDQyxnQkFBWTtBQUx5QixHQUF2Qzs7QUFRQTs7Ozs7O0FBTUFqQixpQkFBZUssU0FBZixDQUF5QmEsWUFBekIsR0FBd0MsVUFBU0MsS0FBVCxFQUFnQjtBQUN0RCxRQUFJLENBQUMsS0FBS0MsY0FBTCxDQUFvQkMsS0FBcEIsQ0FBMEJDLEtBQTNCLElBQW9DLENBQUMsS0FBS0YsY0FBTCxDQUFvQkMsS0FBcEIsQ0FBMEJFLE1BQW5FLEVBQTJFO0FBQ3pFLFVBQUlDLE9BQU8sS0FBS3RCLFFBQUwsQ0FBY3VCLHFCQUFkLEVBQVg7QUFDQSxXQUFLQyxXQUFMLEdBQW1CRixLQUFLRCxNQUF4QjtBQUNBLFdBQUtJLFVBQUwsR0FBa0JILEtBQUtGLEtBQXZCO0FBQ0EsV0FBS00sV0FBTCxHQUFtQkMsS0FBS0MsSUFBTCxDQUFVTixLQUFLRixLQUFMLEdBQWFFLEtBQUtGLEtBQWxCLEdBQ3pCRSxLQUFLRCxNQUFMLEdBQWNDLEtBQUtELE1BREosSUFDYyxDQURkLEdBQ2tCLENBRHJDO0FBRUEsV0FBS0gsY0FBTCxDQUFvQkMsS0FBcEIsQ0FBMEJDLEtBQTFCLEdBQWtDLEtBQUtNLFdBQUwsR0FBbUIsSUFBckQ7QUFDQSxXQUFLUixjQUFMLENBQW9CQyxLQUFwQixDQUEwQkUsTUFBMUIsR0FBbUMsS0FBS0ssV0FBTCxHQUFtQixJQUF0RDtBQUNEOztBQUVELFNBQUtSLGNBQUwsQ0FBb0JXLFNBQXBCLENBQThCQyxHQUE5QixDQUFrQyxLQUFLcEIsV0FBTCxDQUFpQkssVUFBbkQ7O0FBRUEsUUFBSUUsTUFBTWMsSUFBTixLQUFlLFdBQWYsSUFBOEIsS0FBS0Msa0JBQXZDLEVBQTJEO0FBQ3pELFdBQUtBLGtCQUFMLEdBQTBCLEtBQTFCO0FBQ0QsS0FGRCxNQUVPO0FBQ0wsVUFBSWYsTUFBTWMsSUFBTixLQUFlLFlBQW5CLEVBQWlDO0FBQy9CLGFBQUtDLGtCQUFMLEdBQTBCLElBQTFCO0FBQ0Q7QUFDRCxVQUFJQyxhQUFhLEtBQUtDLGFBQUwsRUFBakI7QUFDQSxVQUFJRCxhQUFhLENBQWpCLEVBQW9CO0FBQ2xCO0FBQ0Q7QUFDRCxXQUFLRSxhQUFMLENBQW1CLENBQW5CO0FBQ0EsVUFBSUMsUUFBUW5CLE1BQU1vQixhQUFOLENBQW9CZCxxQkFBcEIsRUFBWjtBQUNBLFVBQUllLENBQUo7QUFDQSxVQUFJQyxDQUFKO0FBQ0E7QUFDQSxVQUFJdEIsTUFBTXVCLE9BQU4sS0FBa0IsQ0FBbEIsSUFBdUJ2QixNQUFNd0IsT0FBTixLQUFrQixDQUE3QyxFQUFnRDtBQUM5Q0gsWUFBSVgsS0FBS2UsS0FBTCxDQUFXTixNQUFNaEIsS0FBTixHQUFjLENBQXpCLENBQUo7QUFDQW1CLFlBQUlaLEtBQUtlLEtBQUwsQ0FBV04sTUFBTWYsTUFBTixHQUFlLENBQTFCLENBQUo7QUFDRCxPQUhELE1BR087QUFDTCxZQUFJbUIsVUFBVXZCLE1BQU11QixPQUFOLEtBQWtCRyxTQUFsQixHQUE4QjFCLE1BQU11QixPQUFwQyxHQUE4Q3ZCLE1BQU0yQixPQUFOLENBQWMsQ0FBZCxFQUFpQkosT0FBN0U7QUFDQSxZQUFJQyxVQUFVeEIsTUFBTXdCLE9BQU4sS0FBa0JFLFNBQWxCLEdBQThCMUIsTUFBTXdCLE9BQXBDLEdBQThDeEIsTUFBTTJCLE9BQU4sQ0FBYyxDQUFkLEVBQWlCSCxPQUE3RTtBQUNBSCxZQUFJWCxLQUFLZSxLQUFMLENBQVdGLFVBQVVKLE1BQU1TLElBQTNCLENBQUo7QUFDQU4sWUFBSVosS0FBS2UsS0FBTCxDQUFXRCxVQUFVTCxNQUFNVSxHQUEzQixDQUFKO0FBQ0Q7QUFDRCxXQUFLQyxXQUFMLENBQWlCVCxDQUFqQixFQUFvQkMsQ0FBcEI7QUFDQSxXQUFLUyxlQUFMLENBQXFCLElBQXJCO0FBQ0E5QyxhQUFPK0MscUJBQVAsQ0FBNkIsS0FBS0MsZ0JBQUwsQ0FBc0JDLElBQXRCLENBQTJCLElBQTNCLENBQTdCO0FBQ0Q7QUFDRixHQXpDRDs7QUEyQ0E7Ozs7OztBQU1BckQsaUJBQWVLLFNBQWYsQ0FBeUJpRCxVQUF6QixHQUFzQyxVQUFTbkMsS0FBVCxFQUFnQjtBQUNwRDtBQUNBLFFBQUlBLFNBQVNBLE1BQU1vQyxNQUFOLEtBQWlCLENBQTlCLEVBQWlDO0FBQy9CO0FBQ0E7QUFDQTtBQUNBbkQsYUFBT29ELFVBQVAsQ0FBa0IsWUFBVztBQUMzQixhQUFLcEMsY0FBTCxDQUFvQlcsU0FBcEIsQ0FBOEIwQixNQUE5QixDQUFxQyxLQUFLN0MsV0FBTCxDQUFpQkssVUFBdEQ7QUFDRCxPQUZpQixDQUVoQm9DLElBRmdCLENBRVgsSUFGVyxDQUFsQixFQUVjLENBRmQ7QUFHRDtBQUNGLEdBVkQ7O0FBWUE7OztBQUdBckQsaUJBQWVLLFNBQWYsQ0FBeUJGLElBQXpCLEdBQWdDLFlBQVc7QUFDekMsUUFBSSxLQUFLRCxRQUFULEVBQW1CO0FBQ2pCLFVBQUl3RCxjQUNBLEtBQUt4RCxRQUFMLENBQWM2QixTQUFkLENBQXdCNEIsUUFBeEIsQ0FBaUMsS0FBSy9DLFdBQUwsQ0FBaUJDLGFBQWxELENBREo7QUFFQSxVQUFJLENBQUMsS0FBS1gsUUFBTCxDQUFjNkIsU0FBZCxDQUF3QjRCLFFBQXhCLENBQ0QsS0FBSy9DLFdBQUwsQ0FBaUJFLDJCQURoQixDQUFMLEVBQ21EO0FBQ2pELGFBQUtNLGNBQUwsR0FBc0IsS0FBS2xCLFFBQUwsQ0FBYzBELGFBQWQsQ0FBNEIsTUFDOUMsS0FBS2hELFdBQUwsQ0FBaUJHLE1BREMsQ0FBdEI7QUFFQSxhQUFLOEMsV0FBTCxHQUFtQixDQUFuQjtBQUNBLGFBQUtqQyxXQUFMLEdBQW1CLENBQW5CO0FBQ0EsYUFBS2tDLEVBQUwsR0FBVSxDQUFWO0FBQ0EsYUFBS0MsRUFBTCxHQUFVLENBQVY7O0FBRUE7QUFDQTtBQUNBO0FBQ0EsYUFBSzdCLGtCQUFMLEdBQTBCLEtBQTFCOztBQUVBLGFBQUs4QixnQkFBTCxHQUF3QixLQUFLOUMsWUFBTCxDQUFrQm1DLElBQWxCLENBQXVCLElBQXZCLENBQXhCO0FBQ0EsYUFBS25ELFFBQUwsQ0FBYytELGdCQUFkLENBQStCLFdBQS9CLEVBQ0UsS0FBS0QsZ0JBRFA7QUFFQSxhQUFLOUQsUUFBTCxDQUFjK0QsZ0JBQWQsQ0FBK0IsWUFBL0IsRUFDSSxLQUFLRCxnQkFEVDs7QUFHQSxhQUFLRSxjQUFMLEdBQXNCLEtBQUtaLFVBQUwsQ0FBZ0JELElBQWhCLENBQXFCLElBQXJCLENBQXRCO0FBQ0EsYUFBS25ELFFBQUwsQ0FBYytELGdCQUFkLENBQStCLFNBQS9CLEVBQTBDLEtBQUtDLGNBQS9DO0FBQ0EsYUFBS2hFLFFBQUwsQ0FBYytELGdCQUFkLENBQStCLFlBQS9CLEVBQTZDLEtBQUtDLGNBQWxEO0FBQ0EsYUFBS2hFLFFBQUwsQ0FBYytELGdCQUFkLENBQStCLFVBQS9CLEVBQTJDLEtBQUtDLGNBQWhEO0FBQ0EsYUFBS2hFLFFBQUwsQ0FBYytELGdCQUFkLENBQStCLE1BQS9CLEVBQXVDLEtBQUtDLGNBQTVDOztBQUVBOzs7O0FBSUEsYUFBSzlCLGFBQUwsR0FBcUIsWUFBVztBQUM5QixpQkFBTyxLQUFLeUIsV0FBWjtBQUNELFNBRkQ7O0FBSUE7Ozs7QUFJQSxhQUFLeEIsYUFBTCxHQUFxQixVQUFTOEIsRUFBVCxFQUFhO0FBQ2hDLGVBQUtOLFdBQUwsR0FBbUJNLEVBQW5CO0FBQ0QsU0FGRDs7QUFJQTs7OztBQUlBLGFBQUtDLGdCQUFMLEdBQXdCLFlBQVc7QUFDakMsaUJBQU8sS0FBS2hELGNBQVo7QUFDRCxTQUZEOztBQUlBOzs7OztBQUtBLGFBQUs2QixXQUFMLEdBQW1CLFVBQVNvQixJQUFULEVBQWVDLElBQWYsRUFBcUI7QUFDdEMsZUFBS1IsRUFBTCxHQUFVTyxJQUFWO0FBQ0EsZUFBS04sRUFBTCxHQUFVTyxJQUFWO0FBQ0QsU0FIRDs7QUFLQTs7OztBQUlBLGFBQUtwQixlQUFMLEdBQXVCLFVBQVNxQixLQUFULEVBQWdCO0FBQ3JDLGNBQUksS0FBS25ELGNBQUwsS0FBd0IsSUFBNUIsRUFBa0M7QUFDaEMsZ0JBQUlvRCxlQUFKO0FBQ0EsZ0JBQUlDLEtBQUo7QUFDQSxnQkFBSUMsSUFBSjtBQUNBLGdCQUFJQyxTQUFTLGVBQWUsS0FBS2IsRUFBcEIsR0FBeUIsTUFBekIsR0FBa0MsS0FBS0MsRUFBdkMsR0FBNEMsS0FBekQ7O0FBRUEsZ0JBQUlRLEtBQUosRUFBVztBQUNURSxzQkFBUSxLQUFLbkUsU0FBTCxDQUFlQyxhQUF2QjtBQUNBbUUscUJBQU8sS0FBS3BFLFNBQUwsQ0FBZUUsWUFBdEI7QUFDRCxhQUhELE1BR087QUFDTGlFLHNCQUFRLEtBQUtuRSxTQUFMLENBQWVLLFdBQXZCO0FBQ0ErRCxxQkFBTyxLQUFLOUMsV0FBTCxHQUFtQixJQUExQjtBQUNBLGtCQUFJOEIsV0FBSixFQUFpQjtBQUNmaUIseUJBQVMsZUFBZSxLQUFLaEQsVUFBTCxHQUFrQixDQUFqQyxHQUFxQyxNQUFyQyxHQUNQLEtBQUtELFdBQUwsR0FBbUIsQ0FEWixHQUNnQixLQUR6QjtBQUVEO0FBQ0Y7O0FBRUQ4Qyw4QkFBa0IsMkJBQTJCRyxNQUEzQixHQUFvQ0YsS0FBdEQ7O0FBRUEsaUJBQUtyRCxjQUFMLENBQW9CQyxLQUFwQixDQUEwQnVELGVBQTFCLEdBQTRDSixlQUE1QztBQUNBLGlCQUFLcEQsY0FBTCxDQUFvQkMsS0FBcEIsQ0FBMEJ3RCxXQUExQixHQUF3Q0wsZUFBeEM7QUFDQSxpQkFBS3BELGNBQUwsQ0FBb0JDLEtBQXBCLENBQTBCeUQsU0FBMUIsR0FBc0NOLGVBQXRDOztBQUVBLGdCQUFJRCxLQUFKLEVBQVc7QUFDVCxtQkFBS25ELGNBQUwsQ0FBb0JXLFNBQXBCLENBQThCMEIsTUFBOUIsQ0FBcUMsS0FBSzdDLFdBQUwsQ0FBaUJJLFlBQXREO0FBQ0QsYUFGRCxNQUVPO0FBQ0wsbUJBQUtJLGNBQUwsQ0FBb0JXLFNBQXBCLENBQThCQyxHQUE5QixDQUFrQyxLQUFLcEIsV0FBTCxDQUFpQkksWUFBbkQ7QUFDRDtBQUNGO0FBQ0YsU0EvQkQ7O0FBaUNBOzs7QUFHQSxhQUFLb0MsZ0JBQUwsR0FBd0IsWUFBVztBQUNqQyxjQUFJLEtBQUtTLFdBQUwsS0FBcUIsQ0FBekIsRUFBNEI7QUFDMUJ6RCxtQkFBTytDLHFCQUFQLENBQTZCLEtBQUtDLGdCQUFMLENBQXNCQyxJQUF0QixDQUEyQixJQUEzQixDQUE3QjtBQUNELFdBRkQsTUFFTztBQUNMLGlCQUFLSCxlQUFMLENBQXFCLEtBQXJCO0FBQ0Q7QUFDRixTQU5EO0FBT0Q7QUFDRjtBQUNGLEdBakhEOztBQW1IQTtBQUNBO0FBQ0E2QixtQkFBaUJDLFFBQWpCLENBQTBCO0FBQ3hCQyxpQkFBYWpGLGNBRFc7QUFFeEJrRixtQkFBZSxnQkFGUztBQUd4QkMsY0FBVSxzQkFIYztBQUl4QkMsWUFBUTtBQUpnQixHQUExQjtBQU1ELENBbFBEIiwiZmlsZSI6InJpcHBsZS5qcyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogQGxpY2Vuc2VcbiAqIENvcHlyaWdodCAyMDE1IEdvb2dsZSBJbmMuIEFsbCBSaWdodHMgUmVzZXJ2ZWQuXG4gKlxuICogTGljZW5zZWQgdW5kZXIgdGhlIEFwYWNoZSBMaWNlbnNlLCBWZXJzaW9uIDIuMCAodGhlIFwiTGljZW5zZVwiKTtcbiAqIHlvdSBtYXkgbm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2Ugd2l0aCB0aGUgTGljZW5zZS5cbiAqIFlvdSBtYXkgb2J0YWluIGEgY29weSBvZiB0aGUgTGljZW5zZSBhdFxuICpcbiAqICAgICAgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wXG4gKlxuICogVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2FibGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZVxuICogZGlzdHJpYnV0ZWQgdW5kZXIgdGhlIExpY2Vuc2UgaXMgZGlzdHJpYnV0ZWQgb24gYW4gXCJBUyBJU1wiIEJBU0lTLFxuICogV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuXG4gKiBTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kXG4gKiBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS5cbiAqL1xuXG4oZnVuY3Rpb24oKSB7XG4gICd1c2Ugc3RyaWN0JztcblxuICAvKipcbiAgICogQ2xhc3MgY29uc3RydWN0b3IgZm9yIFJpcHBsZSBNREwgY29tcG9uZW50LlxuICAgKiBJbXBsZW1lbnRzIE1ETCBjb21wb25lbnQgZGVzaWduIHBhdHRlcm4gZGVmaW5lZCBhdDpcbiAgICogaHR0cHM6Ly9naXRodWIuY29tL2phc29ubWF5ZXMvbWRsLWNvbXBvbmVudC1kZXNpZ24tcGF0dGVyblxuICAgKlxuICAgKiBAY29uc3RydWN0b3JcbiAgICogQHBhcmFtIHtIVE1MRWxlbWVudH0gZWxlbWVudCBUaGUgZWxlbWVudCB0aGF0IHdpbGwgYmUgdXBncmFkZWQuXG4gICAqL1xuICB2YXIgTWF0ZXJpYWxSaXBwbGUgPSBmdW5jdGlvbiBNYXRlcmlhbFJpcHBsZShlbGVtZW50KSB7XG4gICAgdGhpcy5lbGVtZW50XyA9IGVsZW1lbnQ7XG5cbiAgICAvLyBJbml0aWFsaXplIGluc3RhbmNlLlxuICAgIHRoaXMuaW5pdCgpO1xuICB9O1xuICB3aW5kb3dbJ01hdGVyaWFsUmlwcGxlJ10gPSBNYXRlcmlhbFJpcHBsZTtcblxuICAvKipcbiAgICogU3RvcmUgY29uc3RhbnRzIGluIG9uZSBwbGFjZSBzbyB0aGV5IGNhbiBiZSB1cGRhdGVkIGVhc2lseS5cbiAgICpcbiAgICogQGVudW0ge3N0cmluZyB8IG51bWJlcn1cbiAgICogQHByaXZhdGVcbiAgICovXG4gIE1hdGVyaWFsUmlwcGxlLnByb3RvdHlwZS5Db25zdGFudF8gPSB7XG4gICAgSU5JVElBTF9TQ0FMRTogJ3NjYWxlKDAuMDAwMSwgMC4wMDAxKScsXG4gICAgSU5JVElBTF9TSVpFOiAnMXB4JyxcbiAgICBJTklUSUFMX09QQUNJVFk6ICcwLjQnLFxuICAgIEZJTkFMX09QQUNJVFk6ICcwJyxcbiAgICBGSU5BTF9TQ0FMRTogJydcbiAgfTtcblxuICAvKipcbiAgICogU3RvcmUgc3RyaW5ncyBmb3IgY2xhc3MgbmFtZXMgZGVmaW5lZCBieSB0aGlzIGNvbXBvbmVudCB0aGF0IGFyZSB1c2VkIGluXG4gICAqIEphdmFTY3JpcHQuIFRoaXMgYWxsb3dzIHVzIHRvIHNpbXBseSBjaGFuZ2UgaXQgaW4gb25lIHBsYWNlIHNob3VsZCB3ZVxuICAgKiBkZWNpZGUgdG8gbW9kaWZ5IGF0IGEgbGF0ZXIgZGF0ZS5cbiAgICpcbiAgICogQGVudW0ge3N0cmluZ31cbiAgICogQHByaXZhdGVcbiAgICovXG4gIE1hdGVyaWFsUmlwcGxlLnByb3RvdHlwZS5Dc3NDbGFzc2VzXyA9IHtcbiAgICBSSVBQTEVfQ0VOVEVSOiAnbWRsLXJpcHBsZS0tY2VudGVyJyxcbiAgICBSSVBQTEVfRUZGRUNUX0lHTk9SRV9FVkVOVFM6ICdtZGwtanMtcmlwcGxlLWVmZmVjdC0taWdub3JlLWV2ZW50cycsXG4gICAgUklQUExFOiAnbWRsLXJpcHBsZScsXG4gICAgSVNfQU5JTUFUSU5HOiAnaXMtYW5pbWF0aW5nJyxcbiAgICBJU19WSVNJQkxFOiAnaXMtdmlzaWJsZSdcbiAgfTtcblxuICAvKipcbiAgICogSGFuZGxlIG1vdXNlIC8gZmluZ2VyIGRvd24gb24gZWxlbWVudC5cbiAgICpcbiAgICogQHBhcmFtIHtFdmVudH0gZXZlbnQgVGhlIGV2ZW50IHRoYXQgZmlyZWQuXG4gICAqIEBwcml2YXRlXG4gICAqL1xuICBNYXRlcmlhbFJpcHBsZS5wcm90b3R5cGUuZG93bkhhbmRsZXJfID0gZnVuY3Rpb24oZXZlbnQpIHtcbiAgICBpZiAoIXRoaXMucmlwcGxlRWxlbWVudF8uc3R5bGUud2lkdGggJiYgIXRoaXMucmlwcGxlRWxlbWVudF8uc3R5bGUuaGVpZ2h0KSB7XG4gICAgICB2YXIgcmVjdCA9IHRoaXMuZWxlbWVudF8uZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCk7XG4gICAgICB0aGlzLmJvdW5kSGVpZ2h0ID0gcmVjdC5oZWlnaHQ7XG4gICAgICB0aGlzLmJvdW5kV2lkdGggPSByZWN0LndpZHRoO1xuICAgICAgdGhpcy5yaXBwbGVTaXplXyA9IE1hdGguc3FydChyZWN0LndpZHRoICogcmVjdC53aWR0aCArXG4gICAgICAgICAgcmVjdC5oZWlnaHQgKiByZWN0LmhlaWdodCkgKiAyICsgMjtcbiAgICAgIHRoaXMucmlwcGxlRWxlbWVudF8uc3R5bGUud2lkdGggPSB0aGlzLnJpcHBsZVNpemVfICsgJ3B4JztcbiAgICAgIHRoaXMucmlwcGxlRWxlbWVudF8uc3R5bGUuaGVpZ2h0ID0gdGhpcy5yaXBwbGVTaXplXyArICdweCc7XG4gICAgfVxuXG4gICAgdGhpcy5yaXBwbGVFbGVtZW50Xy5jbGFzc0xpc3QuYWRkKHRoaXMuQ3NzQ2xhc3Nlc18uSVNfVklTSUJMRSk7XG5cbiAgICBpZiAoZXZlbnQudHlwZSA9PT0gJ21vdXNlZG93bicgJiYgdGhpcy5pZ25vcmluZ01vdXNlRG93bl8pIHtcbiAgICAgIHRoaXMuaWdub3JpbmdNb3VzZURvd25fID0gZmFsc2U7XG4gICAgfSBlbHNlIHtcbiAgICAgIGlmIChldmVudC50eXBlID09PSAndG91Y2hzdGFydCcpIHtcbiAgICAgICAgdGhpcy5pZ25vcmluZ01vdXNlRG93bl8gPSB0cnVlO1xuICAgICAgfVxuICAgICAgdmFyIGZyYW1lQ291bnQgPSB0aGlzLmdldEZyYW1lQ291bnQoKTtcbiAgICAgIGlmIChmcmFtZUNvdW50ID4gMCkge1xuICAgICAgICByZXR1cm47XG4gICAgICB9XG4gICAgICB0aGlzLnNldEZyYW1lQ291bnQoMSk7XG4gICAgICB2YXIgYm91bmQgPSBldmVudC5jdXJyZW50VGFyZ2V0LmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpO1xuICAgICAgdmFyIHg7XG4gICAgICB2YXIgeTtcbiAgICAgIC8vIENoZWNrIGlmIHdlIGFyZSBoYW5kbGluZyBhIGtleWJvYXJkIGNsaWNrLlxuICAgICAgaWYgKGV2ZW50LmNsaWVudFggPT09IDAgJiYgZXZlbnQuY2xpZW50WSA9PT0gMCkge1xuICAgICAgICB4ID0gTWF0aC5yb3VuZChib3VuZC53aWR0aCAvIDIpO1xuICAgICAgICB5ID0gTWF0aC5yb3VuZChib3VuZC5oZWlnaHQgLyAyKTtcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIHZhciBjbGllbnRYID0gZXZlbnQuY2xpZW50WCAhPT0gdW5kZWZpbmVkID8gZXZlbnQuY2xpZW50WCA6IGV2ZW50LnRvdWNoZXNbMF0uY2xpZW50WDtcbiAgICAgICAgdmFyIGNsaWVudFkgPSBldmVudC5jbGllbnRZICE9PSB1bmRlZmluZWQgPyBldmVudC5jbGllbnRZIDogZXZlbnQudG91Y2hlc1swXS5jbGllbnRZO1xuICAgICAgICB4ID0gTWF0aC5yb3VuZChjbGllbnRYIC0gYm91bmQubGVmdCk7XG4gICAgICAgIHkgPSBNYXRoLnJvdW5kKGNsaWVudFkgLSBib3VuZC50b3ApO1xuICAgICAgfVxuICAgICAgdGhpcy5zZXRSaXBwbGVYWSh4LCB5KTtcbiAgICAgIHRoaXMuc2V0UmlwcGxlU3R5bGVzKHRydWUpO1xuICAgICAgd2luZG93LnJlcXVlc3RBbmltYXRpb25GcmFtZSh0aGlzLmFuaW1GcmFtZUhhbmRsZXIuYmluZCh0aGlzKSk7XG4gICAgfVxuICB9O1xuXG4gIC8qKlxuICAgKiBIYW5kbGUgbW91c2UgLyBmaW5nZXIgdXAgb24gZWxlbWVudC5cbiAgICpcbiAgICogQHBhcmFtIHtFdmVudH0gZXZlbnQgVGhlIGV2ZW50IHRoYXQgZmlyZWQuXG4gICAqIEBwcml2YXRlXG4gICAqL1xuICBNYXRlcmlhbFJpcHBsZS5wcm90b3R5cGUudXBIYW5kbGVyXyA9IGZ1bmN0aW9uKGV2ZW50KSB7XG4gICAgLy8gRG9uJ3QgZmlyZSBmb3IgdGhlIGFydGlmaWNpYWwgXCJtb3VzZXVwXCIgZ2VuZXJhdGVkIGJ5IGEgZG91YmxlLWNsaWNrLlxuICAgIGlmIChldmVudCAmJiBldmVudC5kZXRhaWwgIT09IDIpIHtcbiAgICAgIC8vIEFsbG93IGEgcmVwYWludCB0byBvY2N1ciBiZWZvcmUgcmVtb3ZpbmcgdGhpcyBjbGFzcywgc28gdGhlIGFuaW1hdGlvblxuICAgICAgLy8gc2hvd3MgZm9yIHRhcCBldmVudHMsIHdoaWNoIHNlZW0gdG8gdHJpZ2dlciBhIG1vdXNldXAgdG9vIHNvb24gYWZ0ZXJcbiAgICAgIC8vIG1vdXNlZG93bi5cbiAgICAgIHdpbmRvdy5zZXRUaW1lb3V0KGZ1bmN0aW9uKCkge1xuICAgICAgICB0aGlzLnJpcHBsZUVsZW1lbnRfLmNsYXNzTGlzdC5yZW1vdmUodGhpcy5Dc3NDbGFzc2VzXy5JU19WSVNJQkxFKTtcbiAgICAgIH0uYmluZCh0aGlzKSwgMCk7XG4gICAgfVxuICB9O1xuXG4gIC8qKlxuICAgKiBJbml0aWFsaXplIGVsZW1lbnQuXG4gICAqL1xuICBNYXRlcmlhbFJpcHBsZS5wcm90b3R5cGUuaW5pdCA9IGZ1bmN0aW9uKCkge1xuICAgIGlmICh0aGlzLmVsZW1lbnRfKSB7XG4gICAgICB2YXIgcmVjZW50ZXJpbmcgPVxuICAgICAgICAgIHRoaXMuZWxlbWVudF8uY2xhc3NMaXN0LmNvbnRhaW5zKHRoaXMuQ3NzQ2xhc3Nlc18uUklQUExFX0NFTlRFUik7XG4gICAgICBpZiAoIXRoaXMuZWxlbWVudF8uY2xhc3NMaXN0LmNvbnRhaW5zKFxuICAgICAgICAgIHRoaXMuQ3NzQ2xhc3Nlc18uUklQUExFX0VGRkVDVF9JR05PUkVfRVZFTlRTKSkge1xuICAgICAgICB0aGlzLnJpcHBsZUVsZW1lbnRfID0gdGhpcy5lbGVtZW50Xy5xdWVyeVNlbGVjdG9yKCcuJyArXG4gICAgICAgICAgICB0aGlzLkNzc0NsYXNzZXNfLlJJUFBMRSk7XG4gICAgICAgIHRoaXMuZnJhbWVDb3VudF8gPSAwO1xuICAgICAgICB0aGlzLnJpcHBsZVNpemVfID0gMDtcbiAgICAgICAgdGhpcy54XyA9IDA7XG4gICAgICAgIHRoaXMueV8gPSAwO1xuXG4gICAgICAgIC8vIFRvdWNoIHN0YXJ0IHByb2R1Y2VzIGEgY29tcGF0IG1vdXNlIGRvd24gZXZlbnQsIHdoaWNoIHdvdWxkIGNhdXNlIGFcbiAgICAgICAgLy8gc2Vjb25kIHJpcHBsZXMuIFRvIGF2b2lkIHRoYXQsIHdlIHVzZSB0aGlzIHByb3BlcnR5IHRvIGlnbm9yZSB0aGUgZmlyc3RcbiAgICAgICAgLy8gbW91c2UgZG93biBhZnRlciBhIHRvdWNoIHN0YXJ0LlxuICAgICAgICB0aGlzLmlnbm9yaW5nTW91c2VEb3duXyA9IGZhbHNlO1xuXG4gICAgICAgIHRoaXMuYm91bmREb3duSGFuZGxlciA9IHRoaXMuZG93bkhhbmRsZXJfLmJpbmQodGhpcyk7XG4gICAgICAgIHRoaXMuZWxlbWVudF8uYWRkRXZlbnRMaXN0ZW5lcignbW91c2Vkb3duJyxcbiAgICAgICAgICB0aGlzLmJvdW5kRG93bkhhbmRsZXIpO1xuICAgICAgICB0aGlzLmVsZW1lbnRfLmFkZEV2ZW50TGlzdGVuZXIoJ3RvdWNoc3RhcnQnLFxuICAgICAgICAgICAgdGhpcy5ib3VuZERvd25IYW5kbGVyKTtcblxuICAgICAgICB0aGlzLmJvdW5kVXBIYW5kbGVyID0gdGhpcy51cEhhbmRsZXJfLmJpbmQodGhpcyk7XG4gICAgICAgIHRoaXMuZWxlbWVudF8uYWRkRXZlbnRMaXN0ZW5lcignbW91c2V1cCcsIHRoaXMuYm91bmRVcEhhbmRsZXIpO1xuICAgICAgICB0aGlzLmVsZW1lbnRfLmFkZEV2ZW50TGlzdGVuZXIoJ21vdXNlbGVhdmUnLCB0aGlzLmJvdW5kVXBIYW5kbGVyKTtcbiAgICAgICAgdGhpcy5lbGVtZW50Xy5hZGRFdmVudExpc3RlbmVyKCd0b3VjaGVuZCcsIHRoaXMuYm91bmRVcEhhbmRsZXIpO1xuICAgICAgICB0aGlzLmVsZW1lbnRfLmFkZEV2ZW50TGlzdGVuZXIoJ2JsdXInLCB0aGlzLmJvdW5kVXBIYW5kbGVyKTtcblxuICAgICAgICAvKipcbiAgICAgICAgICogR2V0dGVyIGZvciBmcmFtZUNvdW50Xy5cbiAgICAgICAgICogQHJldHVybiB7bnVtYmVyfSB0aGUgZnJhbWUgY291bnQuXG4gICAgICAgICAqL1xuICAgICAgICB0aGlzLmdldEZyYW1lQ291bnQgPSBmdW5jdGlvbigpIHtcbiAgICAgICAgICByZXR1cm4gdGhpcy5mcmFtZUNvdW50XztcbiAgICAgICAgfTtcblxuICAgICAgICAvKipcbiAgICAgICAgICogU2V0dGVyIGZvciBmcmFtZUNvdW50Xy5cbiAgICAgICAgICogQHBhcmFtIHtudW1iZXJ9IGZDIHRoZSBmcmFtZSBjb3VudC5cbiAgICAgICAgICovXG4gICAgICAgIHRoaXMuc2V0RnJhbWVDb3VudCA9IGZ1bmN0aW9uKGZDKSB7XG4gICAgICAgICAgdGhpcy5mcmFtZUNvdW50XyA9IGZDO1xuICAgICAgICB9O1xuXG4gICAgICAgIC8qKlxuICAgICAgICAgKiBHZXR0ZXIgZm9yIHJpcHBsZUVsZW1lbnRfLlxuICAgICAgICAgKiBAcmV0dXJuIHtFbGVtZW50fSB0aGUgcmlwcGxlIGVsZW1lbnQuXG4gICAgICAgICAqL1xuICAgICAgICB0aGlzLmdldFJpcHBsZUVsZW1lbnQgPSBmdW5jdGlvbigpIHtcbiAgICAgICAgICByZXR1cm4gdGhpcy5yaXBwbGVFbGVtZW50XztcbiAgICAgICAgfTtcblxuICAgICAgICAvKipcbiAgICAgICAgICogU2V0cyB0aGUgcmlwcGxlIFggYW5kIFkgY29vcmRpbmF0ZXMuXG4gICAgICAgICAqIEBwYXJhbSAge251bWJlcn0gbmV3WCB0aGUgbmV3IFggY29vcmRpbmF0ZVxuICAgICAgICAgKiBAcGFyYW0gIHtudW1iZXJ9IG5ld1kgdGhlIG5ldyBZIGNvb3JkaW5hdGVcbiAgICAgICAgICovXG4gICAgICAgIHRoaXMuc2V0UmlwcGxlWFkgPSBmdW5jdGlvbihuZXdYLCBuZXdZKSB7XG4gICAgICAgICAgdGhpcy54XyA9IG5ld1g7XG4gICAgICAgICAgdGhpcy55XyA9IG5ld1k7XG4gICAgICAgIH07XG5cbiAgICAgICAgLyoqXG4gICAgICAgICAqIFNldHMgdGhlIHJpcHBsZSBzdHlsZXMuXG4gICAgICAgICAqIEBwYXJhbSAge2Jvb2xlYW59IHN0YXJ0IHdoZXRoZXIgb3Igbm90IHRoaXMgaXMgdGhlIHN0YXJ0IGZyYW1lLlxuICAgICAgICAgKi9cbiAgICAgICAgdGhpcy5zZXRSaXBwbGVTdHlsZXMgPSBmdW5jdGlvbihzdGFydCkge1xuICAgICAgICAgIGlmICh0aGlzLnJpcHBsZUVsZW1lbnRfICE9PSBudWxsKSB7XG4gICAgICAgICAgICB2YXIgdHJhbnNmb3JtU3RyaW5nO1xuICAgICAgICAgICAgdmFyIHNjYWxlO1xuICAgICAgICAgICAgdmFyIHNpemU7XG4gICAgICAgICAgICB2YXIgb2Zmc2V0ID0gJ3RyYW5zbGF0ZSgnICsgdGhpcy54XyArICdweCwgJyArIHRoaXMueV8gKyAncHgpJztcblxuICAgICAgICAgICAgaWYgKHN0YXJ0KSB7XG4gICAgICAgICAgICAgIHNjYWxlID0gdGhpcy5Db25zdGFudF8uSU5JVElBTF9TQ0FMRTtcbiAgICAgICAgICAgICAgc2l6ZSA9IHRoaXMuQ29uc3RhbnRfLklOSVRJQUxfU0laRTtcbiAgICAgICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgICAgIHNjYWxlID0gdGhpcy5Db25zdGFudF8uRklOQUxfU0NBTEU7XG4gICAgICAgICAgICAgIHNpemUgPSB0aGlzLnJpcHBsZVNpemVfICsgJ3B4JztcbiAgICAgICAgICAgICAgaWYgKHJlY2VudGVyaW5nKSB7XG4gICAgICAgICAgICAgICAgb2Zmc2V0ID0gJ3RyYW5zbGF0ZSgnICsgdGhpcy5ib3VuZFdpZHRoIC8gMiArICdweCwgJyArXG4gICAgICAgICAgICAgICAgICB0aGlzLmJvdW5kSGVpZ2h0IC8gMiArICdweCknO1xuICAgICAgICAgICAgICB9XG4gICAgICAgICAgICB9XG5cbiAgICAgICAgICAgIHRyYW5zZm9ybVN0cmluZyA9ICd0cmFuc2xhdGUoLTUwJSwgLTUwJSkgJyArIG9mZnNldCArIHNjYWxlO1xuXG4gICAgICAgICAgICB0aGlzLnJpcHBsZUVsZW1lbnRfLnN0eWxlLndlYmtpdFRyYW5zZm9ybSA9IHRyYW5zZm9ybVN0cmluZztcbiAgICAgICAgICAgIHRoaXMucmlwcGxlRWxlbWVudF8uc3R5bGUubXNUcmFuc2Zvcm0gPSB0cmFuc2Zvcm1TdHJpbmc7XG4gICAgICAgICAgICB0aGlzLnJpcHBsZUVsZW1lbnRfLnN0eWxlLnRyYW5zZm9ybSA9IHRyYW5zZm9ybVN0cmluZztcblxuICAgICAgICAgICAgaWYgKHN0YXJ0KSB7XG4gICAgICAgICAgICAgIHRoaXMucmlwcGxlRWxlbWVudF8uY2xhc3NMaXN0LnJlbW92ZSh0aGlzLkNzc0NsYXNzZXNfLklTX0FOSU1BVElORyk7XG4gICAgICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgICAgICB0aGlzLnJpcHBsZUVsZW1lbnRfLmNsYXNzTGlzdC5hZGQodGhpcy5Dc3NDbGFzc2VzXy5JU19BTklNQVRJTkcpO1xuICAgICAgICAgICAgfVxuICAgICAgICAgIH1cbiAgICAgICAgfTtcblxuICAgICAgICAvKipcbiAgICAgICAgICogSGFuZGxlcyBhbiBhbmltYXRpb24gZnJhbWUuXG4gICAgICAgICAqL1xuICAgICAgICB0aGlzLmFuaW1GcmFtZUhhbmRsZXIgPSBmdW5jdGlvbigpIHtcbiAgICAgICAgICBpZiAodGhpcy5mcmFtZUNvdW50Xy0tID4gMCkge1xuICAgICAgICAgICAgd2luZG93LnJlcXVlc3RBbmltYXRpb25GcmFtZSh0aGlzLmFuaW1GcmFtZUhhbmRsZXIuYmluZCh0aGlzKSk7XG4gICAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIHRoaXMuc2V0UmlwcGxlU3R5bGVzKGZhbHNlKTtcbiAgICAgICAgICB9XG4gICAgICAgIH07XG4gICAgICB9XG4gICAgfVxuICB9O1xuXG4gIC8vIFRoZSBjb21wb25lbnQgcmVnaXN0ZXJzIGl0c2VsZi4gSXQgY2FuIGFzc3VtZSBjb21wb25lbnRIYW5kbGVyIGlzIGF2YWlsYWJsZVxuICAvLyBpbiB0aGUgZ2xvYmFsIHNjb3BlLlxuICBjb21wb25lbnRIYW5kbGVyLnJlZ2lzdGVyKHtcbiAgICBjb25zdHJ1Y3RvcjogTWF0ZXJpYWxSaXBwbGUsXG4gICAgY2xhc3NBc1N0cmluZzogJ01hdGVyaWFsUmlwcGxlJyxcbiAgICBjc3NDbGFzczogJ21kbC1qcy1yaXBwbGUtZWZmZWN0JyxcbiAgICB3aWRnZXQ6IGZhbHNlXG4gIH0pO1xufSkoKTtcbiJdfQ==
